[package]
name = "rusqlls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread", "sync", "io-std", "io-util", "time", "tracing", "fs"] }
tower-lsp = "0.18.0"
